perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim0
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim1
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim2
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim3
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim4
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim5
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim6
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim7
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim8
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim9
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim10
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim11
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim12
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim13
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim14
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim15
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim16
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim17
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim18
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim19
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim20
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim21
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim22
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim23
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim24
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim25
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim26
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim27
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim28
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim29
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim30
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim31
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim32
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim33
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim34
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim35
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim36
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim37
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim38
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim39
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim40
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim41
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim42
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim43
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim44
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim45
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim46
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim47
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim48
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim49
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim50
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim51
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim52
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim53
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim54
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim55
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim56
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim57
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim58
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim59
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim60
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim61
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim62
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim63
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim64
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim65
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim66
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim67
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim68
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim69
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim70
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim71
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim72
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim73
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim74
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim75
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim76
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim77
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim78
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim79
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim80
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim81
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim82
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim83
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim84
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim85
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim86
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim87
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim88
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim89
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim90
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim91
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim92
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim93
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim94
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim95
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim96
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim97
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim98
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim99
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim100
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim101
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim102
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim103
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim104
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim105
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim106
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim107
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim108
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim109
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim110
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim111
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim112
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim113
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim114
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim115
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim116
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim117
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim118
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim119
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim120
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim121
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim122
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim123
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim124
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim125
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim126
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim127
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim128
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim129
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim130
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim131
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim132
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim133
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim134
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim135
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim136
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim137
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim138
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim139
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim140
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim141
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim142
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim143
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim144
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim145
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim146
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim147
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim148
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim149
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim150
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim151
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim152
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim153
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim154
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim155
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim156
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim157
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim158
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim159
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim160
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim161
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim162
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim163
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim164
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim165
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim166
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim167
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim168
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim169
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim170
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim171
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim172
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim173
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim174
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim175
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim176
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim177
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim178
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim179
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim180
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim181
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim182
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim183
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim184
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim185
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim186
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim187
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim188
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim189
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim190
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim191
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim192
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim193
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim194
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim195
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim196
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim197
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim198
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim199
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim200
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim201
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim202
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim203
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim204
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim205
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim206
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim207
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim208
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim209
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim210
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim211
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim212
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim213
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim214
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim215
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim216
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim217
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim218
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim219
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim220
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim221
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim222
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim223
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim224
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim225
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim226
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim227
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim228
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim229
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim230
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim231
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim232
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim233
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim234
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim235
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim236
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim237
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim238
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim239
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim240
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim241
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim242
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim243
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim244
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim245
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim246
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim247
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim248
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim249
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim250
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim251
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim252
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim253
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim254
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim255
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim256
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim257
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim258
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim259
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim260
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim261
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim262
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim263
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim264
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim265
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim266
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim267
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim268
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim269
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim270
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim271
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim272
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim273
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim274
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim275
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim276
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim277
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim278
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim279
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim280
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim281
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim282
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim283
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim284
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim285
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim286
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim287
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim288
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim289
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim290
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim291
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim292
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim293
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim294
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim295
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim296
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim297
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim298
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim299
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim300
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim301
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim302
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim303
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim304
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim305
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim306
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim307
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim308
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim309
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim310
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim311
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim312
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim313
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim314
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim315
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim316
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim317
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim318
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim319
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim320
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim321
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim322
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim323
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim324
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim325
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim326
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim327
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim328
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim329
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim330
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim331
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim332
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim333
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim334
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim335
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim336
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim337
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim338
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim339
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim340
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim341
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim342
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim343
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim344
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim345
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim346
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim347
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim348
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim349
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim350
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim351
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim352
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim353
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim354
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim355
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim356
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim357
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim358
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim359
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim360
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim361
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim362
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim363
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim364
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim365
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim366
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim367
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim368
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim369
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim370
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim371
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim372
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim373
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim374
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim375
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim376
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim377
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim378
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim379
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim380
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim381
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim382
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim383
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim384
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim385
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim386
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim387
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim388
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim389
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim390
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim391
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim392
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim393
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim394
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim395
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim396
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim397
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim398
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim399
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim400
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim401
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim402
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim403
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim404
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim405
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim406
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim407
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim408
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim409
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim410
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim411
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim412
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim413
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim414
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim415
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim416
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim417
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim418
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim419
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim420
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim421
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim422
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim423
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim424
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim425
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim426
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim427
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim428
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim429
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim430
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim431
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim432
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim433
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim434
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim435
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim436
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim437
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim438
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim439
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim440
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim441
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim442
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim443
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim444
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim445
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim446
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim447
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim448
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim449
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim450
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim451
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim452
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim453
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim454
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim455
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim456
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim457
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim458
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim459
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim460
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim461
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim462
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim463
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim464
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim465
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim466
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim467
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim468
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim469
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim470
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim471
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim472
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim473
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim474
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim475
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim476
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim477
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim478
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim479
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim480
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim481
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim482
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim483
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim484
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim485
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim486
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim487
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim488
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim489
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim490
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim491
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim492
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim493
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim494
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim495
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim496
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim497
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim498
perl fasta/simuG.pl -refseq fasta/ref.genome.fa -snp_count 10000 -prefix fasta/sim499
